### ISSUE TITLE
Request: Having additional parameters to commandline

### ISSUE THREAD

**Issue by sakamoto-neko** [felipemanga/ProjectABE#44]
Would it be possible to add other parameters to cmd, such as for fullscreen and rotating screen to vertical on startup? Thanks for your great work on this emulator!

**Comment by felipemanga** [comment]
Either `--skin=Microcard` (vertical) or maybe `--skin=BareFit`?
https://github.com/felipemanga/ProjectABE/releases/tag/v0.8.10

**Comment by sakamoto-neko** [comment]
Works well, thanks!
