### ISSUE TITLE
Arduboy2::drawFastVLine causes TypeError

### ISSUE THREAD

**Issue by soxfox** [felipemanga/ProjectABE#45]
Whenever I use `drawFastVLine` in a sketch, an error appears in the Log tab: "TypeError: Cannot set property 'title' of undefined." The issue does not appear with `drawFastHLine`, or any other function I've tested.

Here is the code I used to test:
```cpp
#include <Arduboy2.h>

Arduboy2 ab;

void setup() {
  ab.begin();
  ab.clear();
  ab.drawFastVLine(64, 0, 64, WHITE);
  ab.display();
}

void loop() {
  
}
```

EDIT: It works fine using Arduboy2Base, but not Arduboy2

**Comment by felipemanga** [comment]
Confirmed and fixed in the online version. 
Thanks for the report! :)

**Comment by GamesJ** [comment]
In the new Version 0.78 happened a similar issue with the drawRect function. Like the last issue it works fine using Arduboy2Base, but not Arduboy2.

**Comment by soxfox** [comment]
Is this the offline version?

**Comment by GamesJ** [comment]
No

**Comment by soxfox** [comment]
Odd. The web version shows version 0.8.10 for me. Try clearing your browser cache and reloading the page.

P. S. This appears to be the same issue, as `drawRect` uses `drawFastVLine`.

**Comment by GamesJ** [comment]
Sorry for the inconvenience but the error went away as I just tested it again using Arduboy2. I don't know how the error occurred.Thanks for the help,
