### ISSUE TITLE
Basic Tunes Example Does not Run

### ISSUE THREAD

**Issue by cogmind** [felipemanga/ProjectABE#46]
Building
    https://github.com/Arduboy/Arduboy/blob/master/examples/Tunes/Tunes.ino

results in the following error:

> 
> ERROR: Error: Command failed: /app/arduino --board arduino:avr:leonardo --pref build.path=/app/public/builds/3 --verify/app/builds/3/test1.ino
> ....
> Verifying...
> disassembly.s:20: error: invalid digit "8" in octal constant
> 2c: 0c 94 36 08 jmp 0x106c ; 0x106c <__vector_11>

It's not possible to copy the contents of the Log output, so I won't type the rest. Finally:

> 
> "disassembly.s:62: error: expected declaration before '}' token
> cf: 3e 7c 3e 1c 18 3c 7e 3c 18 1c 57 7d 57 1c 1c 5e >||>..<~<..W~}W..^
> 
> exit status 1

The same code does build without errors in the Arduino IDE.

**Comment by felipemanga** [comment]
Thanks for the heads-up. Fixed it.
