### ISSUE TITLE
Pulling out emulator code?

### ISSUE THREAD

**Issue by epbarger** [felipemanga/ProjectABE#53]
How difficult would it be to pull the actual emulator code out? I would love to embed the emulator on my own website in the future!

This a really cool project, nice work!

**Comment by felipemanga** [comment]
Hey,
It's already embeddable: just put it in an iframe with the hex and skin parameters and the game will run there. You can clone the gh-pages branch to your own server, if you'd like.
Would that work for you?

**Comment by epbarger** [comment]
Ah, I understand. Yup that'll work! Thanks
